name=MyDHT22
version=1.0.0
author=Fadhil <fadhil.hashim755@tahoo.com>
maintainer=Fadhil <fadhil.hashim755@tahoo.com>
sentence=Lightweight library for DHT22 temperature and humidity sensor.
paragraph=Fast, minimal implementation of DHT22 sensor reading without delay or blocking.
category=Sensors
url=https://github.com/fadhil-1911/MyDHT22
architectures=*
types=arduino