name=MyDHT22
version=1.0.0
author=Fadhil
maintainer=Fadhil
sentence=Library for reading DHT22 sensor without third-party dependencies.
paragraph=A lightweight library to read temperature and humidity from DHT22.
category=Sensors
url=https://github.com/fadhil-1911/MyDHT22
architectures=*
